image: node:18

variables:
  AWS_REGION: eu-central-1

stages:
  - lint
  - deploy_function

lint:
  stage: lint
  before_script:
    - yarn install
  script:
    - yarn lint

production:
  stage: deploy_function
  when: manual
  needs:
    - lint
  before_script:
    - FAILURE_MESSAGE="Must define \$AWS_ACCESS_KEY_ID and \$AWS_SECRET_ACCESS_KEY. Add keys to $CI_PROJECT_URL/-/settings/ci_cd"
    - test -z "$AWS_SECRET_ACCESS_KEY" && echo $FAILURE_MESSAGE && exit 1
    - test -z "$AWS_ACCESS_KEY_ID" && echo $FAILURE_MESSAGE && exit 1
  script:
    - yarn install
    - npm run deploy -- --stage production --verbose
  environment: production
  only:
    - main
